# Generated by Django 3.2 on 2025-12-02 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ERBilling',
            fields=[
                ('uhid', models.CharField(max_length=50)),
                ('patientname', models.CharField(max_length=150)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('phonenumber', models.CharField(blank=True, max_length=20, null=True)),
                ('billnumber', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('doctorname', models.CharField(blank=True, max_length=150, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('payment_mode', models.JSONField(blank=True, null=True)),
                ('procedures', models.JSONField()),
                ('discount_type', models.CharField(blank=True, max_length=10, null=True)),
                ('discount_value', models.FloatField(blank=True, max_length=10, null=True)),
                ('discount_amount', models.FloatField(blank=True, max_length=10, null=True)),
                ('total', models.FloatField()),
                ('net_amount', models.FloatField(blank=True, max_length=10, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('lastmodified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('lastmodified_date', models.DateTimeField(auto_now_add=True)),
                ('billing_status', models.CharField(default='Billed', max_length=10)),
            ],
        ),
    ]
